Save pets level on reload.
Prodigy-Hacking/ProdigyMathGameHacking pull request #824
Opened 2021-03-29 15:05 UTC by hostedposted

## Description
I save pets level in a array in local storage and push an array with id then level of pet for all pets.

Then when you reload a for each loop is done and the pets levels are changed to the ones in local storage,

2021-03-29 17:05 UTC, ArcerionDev commented
Like the idea, but if someone were to switch their pet team, it'd change the level of the new pet.

2021-03-29 17:11 UTC, hostedposted commented
Ok.

2021-03-29 19:02 UTC, ChickenOnYT commented
Then ask them to fix it.

2021-03-29 19:03 UTC, ChickenOnYT requested changes
Fix what Arc said.

2021-03-29 19:42 UTC, hostedposted commented
Oops did not mean to click that.

2021-03-30 00:44 UTC, PatheticMustan commented on willsCheatMenu/src/hacks/pets.ts
> +	})
what the hell is this

2021-03-30 00:44 UTC, PatheticMustan commented on willsCheatMenu/src/index.ts
> +				eval(`_.player.kennel.petTeam[${element[0]+1}].getLevel = () => {return ${element[1]}}`)
I don't know how you managed it but this is one of the worst lines of code I've ever seen

2021-03-30 00:45 UTC, PatheticMustan commented
what is even supposed to happen here

2021-03-30 10:45 UTC, closed without merging